### ISSUE TITLE
The service httpd is dead

### ISSUE THREAD

**Issue by chris-fa** [chef-cookbooks/httpd#101]
### Cookbook version

[Version of the cookbook where you are encountering the issue]
0.4.4
### Chef-client version

[Version of chef-client in your environment]
12.13.37
### Platform Details

[Operating system distribution and release version. Cloud provider if running in the cloud]
bento/centos7.2
### Scenario:

[What you are trying to achieve and you can't?]
I want `httpd` to be started and to keep being started
### Steps to Reproduce:

[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]
Install httpd using this code:

```
httpd_service 'apps' do
    mpm 'prefork'
    action [:create, :start]
    listen_ports ['80', '443']
    run_user node['webserver']['run_user']  # the value is "vagrant"
end

# Add the site configuration
httpd_config 'apps' do
    instance 'apps'
    source 'apps.conf.erb'
    notifies :restart, 'httpd_service[apps]'
end

# Create document rood directory
directory "#{node['webserver']['document_root']}" do
    recursive true
end

# Homepage
template "#{node['webserver']['document_root']}/index.php" do
    source 'index.php.erb'
    mode '0644'
    owner node['webserver']['user']
    group node['webserver']['group']
    action :create_if_missing
end

# Install the mod_php Apache module.
httpd_module 'php' do
    instance 'apps'
end

# Install memcached
package 'memcached'

# Install php-pecl-memcache
package 'php-pecl-memcache' do
    action :install
    notifies :restart, 'httpd_service[apps]'
end

# Install php-pecl-memcached
package 'php-pecl-memcached' do
    action :install
    notifies :restart, 'httpd_service[apps]'
end

# Install php-mysql
package 'php-mysql' do
    action :install
    notifies :restart, 'httpd_service[apps]'
end

# Install php-pdo
package 'php-pdo' do
    action :install
    notifies :restart, 'httpd_service[apps]'
end

# Install php-intl
package 'php-intl' do
    action :install
    notifies :restart, 'httpd_service[apps]'
end

# Install php-mssql
package 'php-mssql' do
  action :install
  notifies :restart, 'httpd_service[apps]'
end
```
### Expected Result:

[What are you expecting to happen as the consequence of above reproduction steps?]
When I provision, `httpd-apps` is up and it keeps being up after every http request.
### Actual Result:

[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
When I provision, `httpd-apps` is dead. After I start it (manually: `service httpd-apps start`) and execute an http request, it dies.

Logs and everything else is in [this SO question](http://stackoverflow.com/questions/40025970/using-the-httpd-chef-cookbook-httpd-is-killed-after-every-request?noredirect=1#comment67364151_40025970)

**Comment by chris-fa** [comment]
Am I doing something wrong, which is the reason httpd dies?

**Comment by cheeseplus** [comment]
It seems from the SO issue that this works fine in kitchen-vagrant but not vagrant directly? Is this issue present still and are you giving the box enough memory?

**Comment by chris-fa** [comment]
@cheeseplus Hmm this is not happening anymore; I can't remember exactly why, but I think it was after I downgraded my bento box to 6.7  (previously on 7.2)

**Comment by cheeseplus** [comment]
OK, if it's not an issue and can't be repro'd I'll close it but we can always open a new issue in the future.
