### ISSUE TITLE
httpd_module php for Amazon AMI

### ISSUE THREAD

**Issue by syd05** [chef-cookbooks/httpd#102]
### Cookbook version

0.4.4
### Chef-client version

12.3.0
### Platform Details

EC2 using Amazon AMI
### Scenario:

Configuring httpd_module 'php' which is not working.
The same works with CentOS 7 with httpd2.4 installed
### Steps to Reproduce:

httpd_module 'php' do
  instance 'default'
end

Tried with php/ php5, httpd2.2 but it does not work with Amazon AMI.
### Actual Result:

ERROR: httpd_module_rhel[php](AppConfig::default line 26) had an error: ArgumentError: You must supply a name when declaring a package resource

**Comment by iennae** [comment]
Hi @syd05,

Apologies for the delay in responding to your issue. If you do something like

httpd_module 'php' do
  instance 'default'
  package_name 'php'
end

Does that solve your problem? I think that https://github.com/chef-cookbooks/httpd/blob/master/libraries/info_module_packages.rb might not have the mapping for what the particular AMI you are using is looking for. How are you installing php?

**Comment by syd05** [comment]
I tried this which works

httpd_module 'php' do
  action :create
  instance 'default'
  package_name 'php54'
end

package_name 'php' might also have worked but it had a dependency on httpd-2.2 where httpd-2.4 was already installed and php54 works with httpd 2.4

Thanx

--Syd

**Comment by iennae** [comment]
Thanks so much for updating this issue with what worked!
