### ISSUE TITLE
Fails to start: File Not Found

### ISSUE THREAD

**Issue by johnjelinek** [chef-cookbooks/httpd#103]
### Cookbook version
`0.4.4`

### Chef-client version
`12.17.44`

### Platform Details
CentOS 7.2 on AWS

### Scenario:
I'm spinning up test kitchen with the docker driver I'm expecting the HTTP server to create and start.

### Steps to Reproduce:
`default.rb`:
```
httpd_service 'default' do
  action [:create, :start]
end
```
append `depends 'httpd', '~> 0.4'` to your `metadata.rb`

### Expected Result:
test kitchen should report that port 80 is listening.

### Actual Result:
        +LoadModule status_module /usr/lib64/httpd/modules/mod_status.so
        - change mode from '' to '0644'
        - change owner from '' to 'root'
        - change group from '' to 'root'

         * httpd_service_rhel_sysvinit[instance1] action start
           * template[/etc/init.d/httpd-instance1] action create

             ================================================================================
             Error executing action `create` on resource 'template[/etc/init.d/httpd-instance1]'
             ================================================================================

             Chef::Exceptions::FileNotFound
             ------------------------------
             Cookbook 'httpd' (0.4.4) does not contain a file at any of these locations:
        templates/centos-7.3.1611/2.4/sysvinit/el-7/httpd.erb
        templates/centos/2.4/sysvinit/el-7/httpd.erb
        templates/default/2.4/sysvinit/el-7/httpd.erb
        templates/2.4/sysvinit/el-7/httpd.erb

             This cookbook _does_ contain: ['/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/mods/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/scripts/a2enmod.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/debian-7/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-5/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-6/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-10.04/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-12.04/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/mods/rhel/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/scripts/a2enmod.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/sysvinit/el-6/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/sysvinit/ubuntu-14.04/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/envvars.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/httpd.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/magic.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/module_load.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.4.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/systemd/httpd.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/systemd/httpd.service.erb']

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/httpd/libraries/httpd_service_rhel_sysvinit.rb

       12:       template "/etc/init.d/#{apache_name}" do
       13:         source "#{new_resource.version}/sysvinit/el-#{elversion}/httpd.erb"
       14:         owner 'root'
       15:         group 'root'
       16:         mode '0755'
       17:         variables(apache_name: apache_name)
       18:         cookbook 'httpd'
       19:         action :create
       20:       end
       21:

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/httpd/libraries/httpd_service_rhel_sysvinit.rb:12:in `block in <class:HttpdServiceRhelSysvinit>'

             template("/etc/init.d/httpd-instance1") do
        action [:create]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        source "2.4/sysvinit/el-7/httpd.erb"
        cookbook "httpd"
        variables {:apache_name=>"httpd-instance1"}
        declared_type :template
        cookbook_name "my_cookbook"
        owner "root"
        group "root"
        mode "0755"
        path "/etc/init.d/httpd-instance1"
             end

             Platform:
             ---------
             x86_64-linux

           ================================================================================
           Error executing action `start` on resource 'httpd_service_rhel_sysvinit[instance1]'
           ================================================================================

           Chef::Exceptions::FileNotFound
           ------------------------------
           template[/etc/init.d/httpd-instance1] (/tmp/kitchen/cache/cookbooks/httpd/libraries/httpd_service_rhel_sysvinit.rb line 12) had an error: Chef::Exceptions::FileNotFound: Cookbook 'httpd' (0.4.4) does not contain a file at any of these locations:
             templates/centos-7.3.1611/2.4/sysvinit/el-7/httpd.erb
             templates/centos/2.4/sysvinit/el-7/httpd.erb
             templates/default/2.4/sysvinit/el-7/httpd.erb
             templates/2.4/sysvinit/el-7/httpd.erb

           This cookbook _does_ contain: ['/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/mods/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/scripts/a2enmod.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/debian-7/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-5/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-6/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-10.04/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-12.04/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/mods/rhel/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/scripts/a2enmod.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/sysvinit/el-6/httpd.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/2.4/sysvinit/ubuntu-14.04/apache2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/envvars.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/httpd.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/magic.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/module_load.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/mpm.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.2.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.4.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/systemd/httpd.conf.erb','/tmp/kitchen/cache/cookbooks/httpd/templates/default/systemd/httpd.service.erb']

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/my_cookbook/recipes/default.rb

             7: httpd_service 'instance1' do
             8:   action [:create, :start]
             9: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/my_cookbook/recipes/default.rb:7:in `from_file'

           httpd_service_rhel_sysvinit("instance1") do
             action [:create, :start]
             updated true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :httpd_service
             cookbook_name "my_cookbook"
             recipe_name "default"
             version "2.4"
             package_name "httpd"
             instance "instance1"
             mpm "event"
             maxclients "0"
             maxconnectionsperchild "0"
             maxrequestworkers "150"
             maxsparethreads "75"
             minsparethreads "25"
             startservers "2"
             threadlimit "64"
             threadsperchild "25"
             run_group "apache"
             run_user "apache"
             servername "c4a061255496"
             modules ["authz_core", "authz_host", "authn_core", "auth_basic", "access_compat", "authn_file", "authz_user", "alias", "dir", "autoindex", "env", "mime", "negotiation", "setenvif", "filter", "deflate", "status"]
             timeout "400"
             log_level "warn"
             maxkeepaliverequests "100"
             keepalivetimeout "5"
             hostname_lookups "off"
             listen_addresses ["0.0.0.0"]
             listen_ports ["80"]
           end

           Platform:
           ---------
           x86_64-linux

       Running handlers:
       [2017-01-20T20:15:36+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-01-20T20:15:36+00:00] ERROR: Exception handlers complete
       Chef Client failed. 61 resources updated in 27 seconds
       [2017-01-20T20:15:36+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-01-20T20:15:36+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-01-20T20:15:36+00:00] ERROR: httpd_service_rhel_sysvinit[instance1] (my_cookbook::default line 7) had an error: Chef::Exceptions::FileNotFound: template[/etc/init.d/httpd-instance1] (/tmp/kitchen/cache/cookbooks/httpd/libraries/httpd_service_rhel_sysvinit.rb line 12) had an error: Chef::Exceptions::FileNotFound: Cookbook 'httpd' (0.4.4) does not contain a file at any of these locations:
         templates/centos-7.3.1611/2.4/sysvinit/el-7/httpd.erb
         templates/centos/2.4/sysvinit/el-7/httpd.erb

**Comment by iennae** [comment]
@johnjelinek Can you provide additional information about how you are configuring this? I've tested on centos 73:

➜  httpd git:(master) ✗ kitchen verify service24-single-centos-73
-----> Starting Kitchen (v1.15.0)
-----> Setting up <service24-single-centos-73>...
       Finished setting up <service24-single-centos-73> (0m0.00s).
-----> Verifying <service24-single-centos-73>...
       Loaded

Target:  ssh://vagrant@127.0.0.1:2200


  Port 80
     ✔  should be listening
     ✔  protocols should include "tcp"

Test Summary: 2 successful, 0 failures, 0 skipped

What I notice is that the default init service for centos 7.3 systemd. Somehow your system is expecting this to be sysvinit. It's also installing the templates for 2.2 rather than 2.4 which is what the "missing file" error is telling you.

**Comment by johnjelinek** [comment]
Can you try running kitchen with the docker driver?

**Comment by iennae** [comment]
I have tested with the dokken driver test kitchen configuration that is also included with this cookbook and I didn't have problems. 

➜  httpd git:(master) chef exec kitchen verify service24-single-centos-7
-----> Starting Kitchen (v1.15.0)
-----> Setting up <service24-single-centos-7>...
       Finished setting up <service24-single-centos-7> (0m0.00s).
-----> Verifying <service24-single-centos-7>...
       Loaded

Target:  docker://f23010a48aba081561ca82e8ba9a8375df7984b8938f9d1ff172792279247e01


  Port 80
     ✔  should be listening
     ✔  protocols should include "tcp"

Test Summary: 2 successful, 0 failures, 0 skipped
       Finished verifying <service24-single-centos-7> (0m1.68s).
-----> Kitchen is finished. (0m3.68s)

In your configuration with test kitchen and docker do you have something to configure it to use systemd?

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which net-tools

**Comment by johnjelinek** [comment]
No, I don't have anything like that.

**Comment by iennae** [comment]
John, 

It looks like your configuration might not be correct based on the problem that you are reporting. Without additional information we can't debug this. I'm unable to replicate the problem that you are reporting so I'm going to go ahead and close this. If you do have more information that you can provide about your problem, you are welcome to reopen this issue.

Thanks.

**Comment by rgriffith** [comment]
I just ran into this on an Amazon Linux server (`amzn-ami-hvm-2017.03.0.20170401-x86_64-gp2 (ami-22ce4934)`). Oddly, does not occur with a previous Amazon Linux AMI (`amzn-ami-hvm-2016.09.1.20170119-x86_64-gp2 (ami-0b33d91d)`). I am not really sure what may have changed between the two AMIs that would have caused the issue.

Let me know if you need anything else, but here is some basic info:

- Using `httpd ~> 4.4.4` (which was bumped to 4.4.5)
- Resource is as follows:

```
httpd_service 'cascade-apache2' do
  version 2.2
  modules ['rewrite', 'ssl', 'proxy', 'proxy_ajp', 'deflate']
  package_name 'httpd'
  action [:create, :start]
end
```

### Relevant stack trace:

```
* template[/etc/init.d/httpd-cascade-apache2] action create[2017-04-06T12:09:39+00:00] INFO: Processing template[/etc/init.d/httpd-cascade-apache2] action create (/var/chef/cache/cookbooks/httpd/libraries/httpd_service_rhel_sysvinit.rb line 12)
  
  ================================================================================
  Error executing action `create` on resource 'template[/etc/init.d/httpd-cascade-apache2]'
  ================================================================================
  
  Chef::Exceptions::FileNotFound
  ------------------------------
  Cookbook 'httpd' (0.4.5) does not contain a file at any of these locations:
    templates/amazon-2017.03/2.2/sysvinit/el-2017/httpd.erb
    templates/amazon/2.2/sysvinit/el-2017/httpd.erb
    templates/default/2.2/sysvinit/el-2017/httpd.erb
    templates/2.2/sysvinit/el-2017/httpd.erb
  
  This cookbook _does_ contain: ['/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-5/httpd.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/scripts/a2enmod.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-6/httpd.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/debian-7/apache2.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.4/mods/rhel/mpm.conf.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/mods/mpm.conf.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.4/sysvinit/el-6/httpd.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.4/sysvinit/ubuntu-14.04/apache2.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.4/scripts/a2enmod.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-10.04/apache2.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-12.04/apache2.erb','/var/chef/cache/cookbooks/httpd/templates/default/magic.erb','/var/chef/cache/cookbooks/httpd/templates/default/module_load.erb','/var/chef/cache/cookbooks/httpd/templates/default/envvars.erb','/var/chef/cache/cookbooks/httpd/templates/default/systemd/httpd.conf.erb','/var/chef/cache/cookbooks/httpd/templates/default/httpd.conf.erb','/var/chef/cache/cookbooks/httpd/templates/default/systemd/httpd.service.erb','/var/chef/cache/cookbooks/httpd/templates/default/mpm.conf.erb','/var/chef/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.4.erb','/var/chef/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.2.erb']
  
  Resource Declaration:
  ---------------------
  # In /var/chef/cache/cookbooks/httpd/libraries/httpd_service_rhel_sysvinit.rb
  
   12:       template "/etc/init.d/#{apache_name}" do
   13:         source "#{new_resource.version}/sysvinit/el-#{elversion}/httpd.erb"
   14:         owner 'root'
   15:         group 'root'
   16:         mode '0755'
   17:         variables(apache_name: apache_name)
   18:         cookbook 'httpd'
   19:         action :create
   20:       end
   21: 
  
  Compiled Resource:
  ------------------
  # Declared in /var/chef/cache/cookbooks/httpd/libraries/httpd_service_rhel_sysvinit.rb:12:in `block in <class:HttpdServiceRhelSysvinit>'
  
  template("/etc/init.d/httpd-cascade-apache2") do
    action [:create]
    retries 0
    retry_delay 2
    default_guard_interpreter :default
    source "2.2/sysvinit/el-2017/httpd.erb"
    cookbook "httpd"
    variables {:apache_name=>"httpd-cascade-apache2"}
    declared_type :template
    cookbook_name "cascade-cloud-instance"
    owner "root"
    group "root"
    mode "0755"
    path "/etc/init.d/httpd-cascade-apache2"
    verifications []
  end
  
  Platform:
  ---------
  x86_64-linux
  
flcc.cascadeserver.com [2017-04-06T12:09:39+00:00] INFO: Running queued delayed notifications before re-raising exception

================================================================================
Error executing action `start` on resource 'httpd_service_rhel_sysvinit[cascade-apache2]'
================================================================================

Chef::Exceptions::FileNotFound
------------------------------
template[/etc/init.d/httpd-cascade-apache2] (/var/chef/cache/cookbooks/httpd/libraries/httpd_service_rhel_sysvinit.rb line 12) had an error: Chef::Exceptions::FileNotFound: Cookbook 'httpd' (0.4.5) does not contain a file at any of these locations:
  templates/amazon-2017.03/2.2/sysvinit/el-2017/httpd.erb
  templates/amazon/2.2/sysvinit/el-2017/httpd.erb
  templates/default/2.2/sysvinit/el-2017/httpd.erb
  templates/2.2/sysvinit/el-2017/httpd.erb

This cookbook _does_ contain: ['/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-5/httpd.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/scripts/a2enmod.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/el-6/httpd.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/debian-7/apache2.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.4/mods/rhel/mpm.conf.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/mods/mpm.conf.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.4/sysvinit/el-6/httpd.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.4/sysvinit/ubuntu-14.04/apache2.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.4/scripts/a2enmod.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-10.04/apache2.erb','/var/chef/cache/cookbooks/httpd/templates/default/2.2/sysvinit/ubuntu-12.04/apache2.erb','/var/chef/cache/cookbooks/httpd/templates/default/magic.erb','/var/chef/cache/cookbooks/httpd/templates/default/module_load.erb','/var/chef/cache/cookbooks/httpd/templates/default/envvars.erb','/var/chef/cache/cookbooks/httpd/templates/default/systemd/httpd.conf.erb','/var/chef/cache/cookbooks/httpd/templates/default/httpd.conf.erb','/var/chef/cache/cookbooks/httpd/templates/default/systemd/httpd.service.erb','/var/chef/cache/cookbooks/httpd/templates/default/mpm.conf.erb','/var/chef/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.4.erb','/var/chef/cache/cookbooks/httpd/templates/default/rhel/sysconfig/httpd-2.2.erb']

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/cascade-cloud-instance/recipes/apache2.rb

 29: httpd_service node['cascade']['apache2']['instance_name'] do
 30:   version node['cascade']['apache2']['version']
 31:   modules ['rewrite', 'ssl', 'proxy', 'proxy_ajp', 'deflate']
 32:   package_name 'httpd'
 33:   action [:create, :start]
 34: end
 35: 

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/cascade-cloud-instance/recipes/apache2.rb:29:in `from_file'

httpd_service_rhel_sysvinit("cascade-apache2") do
  action [:create, :start]
  updated true
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :httpd_service
  cookbook_name "cascade-cloud-instance"
  recipe_name "apache2"
  version "2.2"
  modules ["rewrite", "ssl", "proxy", "proxy_ajp", "deflate"]
  package_name "httpd"
  instance "cascade-apache2"
  mpm "worker"
  maxrequestsperchild "0"
  maxsparethreads "75"
  minsparethreads "25"
  startservers "2"
  threadlimit "64"
  threadsperchild "25"
  run_group "apache"
  run_user "apache"
  servername "ip-172-30-0-98"
  timeout "400"
  log_level "warn"
  maxkeepaliverequests "100"
  keepalivetimeout "5"
  hostname_lookups "off"
  listen_addresses ["0.0.0.0"]
  listen_ports ["80"]
  contact "webmaster@localhost"
end

Platform:
---------
x86_64-linux
```
