### ISSUE TITLE
RHEL 7.2 mod_security module produces mod_security2.so

### ISSUE THREAD

**Issue by kareiva** [chef-cookbooks/httpd#104]
### Cookbook version
0.4.4

### Chef-client version
12.7.2

### Platform Details
Red Hat Enterprise Linux Server release 7.2 (Maipo)

### Scenario:
Install mod_security module

### Steps to Reproduce:
Use the `httpd_module` resource:

```
httpd_module 'security' do
  action :create
end
```

### Expected Result:
`httpd` configuration should be consistent, service should be able to start with `mod_security` enabled.

### Actual Result:
* `/usr/lib64/httpd/modules/mod_security.so` is not found.
* `httpd-default.service` cannot start

### Suggested workaround:
```
httpd_module 'security2' do
  action :create
  module_name 'security2'
  package_name 'mod_security'
end
```

### Suggested fix:

https://github.com/kareiva/httpd/commit/68ef056e8de12fb4baba4d55e04783dcfb572188

**Comment by iennae** [comment]
Thanks for reporting this issue with a suggested fix. version 0.4.5 has this included.
