### ISSUE TITLE
Suggestion: httpd_config should notify the instance to reload

### ISSUE THREAD

**Issue by kkeane** [chef-cookbooks/httpd#13]
The httpd_config resource should notify the corresponding instance to reload or restart. Or if it already does that, it should be documented.

The reason I am suggesting this is that the httpd_config resource already knows which service to notify, while the caller should not necessarily care about the service name.

**Comment by kkeane** [comment]
I think this is moot - I did not realize that the httpd_service resource for that instance serves exactly this purpose.

**Comment by someara** [comment]
It's fucking cool right?
