### ISSUE TITLE
Should refactor resource to match Chef 11/ Chef12 DSL syntax

### ISSUE THREAD

**Issue by someara** [chef-cookbooks/httpd#23]
Use the provides method described here:
https://www.chef.io/blog/2015/02/10/chef-12-provider-resolver/

**Comment by lamont-granquist** [comment]
Actually you want to use `provides` with `supports?` like the service resource internal to Chef uses.

Then if someone installs systemd on RHEL6 or Ubuntu 14.04 you'll pick up the systemd provider dynamically via duck-typing the O/S instead of doing hard coded checks against the platform version.
