### ISSUE TITLE
Error using the httpd_service resource when running on chef-client 12.3

### ISSUE THREAD

**Issue by wonderboyjon** [chef-cookbooks/httpd#34]
After updating to chef-client 12.3 today, the chef-client run fails when attempting to use the httpd_service resource. I have copy and pasted the error output below.

================================================================================
Error executing action `create` on resource 'httpd_service[default]'
================================================================================
ArgumentError
-------------
wrong number of arguments (1 for 0)
Cookbook Trace:
---------------
/var/chef/cache/cookbooks/httpd/libraries/helpers_rhel.rb:13:in `module_name'
/var/chef/cache/cookbooks/httpd/libraries/provider_httpd_service_rhel.rb:45:in `block (3 levels) in <class:Rhel>'
/var/chef/cache/cookbooks/httpd/libraries/provider_httpd_service_rhel.rb:44:in `block (2 levels) in <class:Rhel>'
/var/chef/cache/cookbooks/httpd/libraries/provider_httpd_service_rhel.rb:43:in `each'
/var/chef/cache/cookbooks/httpd/libraries/provider_httpd_service_rhel.rb:43:in `block in <class:Rhel>'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/vshttpd/recipes/default.rb

 38: httpd_service 'default' do
 39:     listen_ports ['80', '443']
 40:     mpm 'prefork'
 41:     run_group httpd_run_group
 42:     run_user httpd_run_user
 43:     action [:create, :start]
 44: end
 45:

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/vshttpd/recipes/default.rb:38:in `from_file'

httpd_service("default") do
  action [:create, :start]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :httpd_service
  cookbook_name "vshttpd"
  recipe_name "default"
  listen_ports ["80", "443"]
  mpm "prefork"
  run_group "asterisk"
  run_user "asterisk"
end

**Comment by someara** [comment]
confirmed. investigating

**Comment by Craft---** [comment]
I don't know if it's helpful or not, and 8 days in I'm positive you've already seen it, but for documentations sake, I can verify that this issue is isolated to chef-client v12.3.0.

**Comment by someara** [comment]
Hi!

Fixed this up in here... forgot to close the issue. Thanks for the ping!

https://github.com/chef-cookbooks/httpd/commit/79fc4c287636576df36347914116d15d8347cf3f

**Comment by Craft---** [comment]
Fantastic, thanks @someara!
