### ISSUE TITLE
Add to README how to include this Cookbook because Chef-solo rejects it as it lacks recipe/default.rb

### ISSUE THREAD

**Issue by lonniev** [chef-cookbooks/httpd#39]
```bash
Chef::Exceptions::RecipeNotFound
==> vmname: --------------------------------
==> vmname: could not find recipe default for cookbook httpd
```

Even though there is a depends line in the calling cookbook:
```ruby
depends 'httpd', '~> 0.2'
```

Please document how to use a recipe-lacking cookbook.

**Comment by someara** [comment]
This cookbook ships resources, not recipes. See the README under "Usage".

Alternatively, look in test/fixtures/cookbooks for complete examples used with test-kitchen

-s

**Comment by lonniev** [comment]
I'd prefer to see this issue remain open as long as there is something not quite expected going on. I am using the cookbook as the documentation and examples illustrate yet nevertheless chef-solo is throwing the RecipeNotFound exception.

**Comment by someara** [comment]
Reopening per gitter.. Can you please provide more context?

Something, somewhere, is referring to the httpd recipe.

cd your_cookbook ;  find . -type f -exec grep httpd {} \;
