### ISSUE TITLE
2.4 doesn't default mpm to event

### ISSUE THREAD

**Issue by spliskamatyshak** [chef-cookbooks/httpd#43]
Running this against CentOS 7.0, it's installing 2.4 as expected, but not defaulting mpm to 'event' as the documentation states.  2.2 on CentOS 6.x does default to mpm 'worker,' however.  Creating the http_service and setting "mpm 'event'" also doesn't force the issue and still runs prefork on CentOS 7.0.

**Comment by spliskamatyshak** [comment]
This is my hammer before this is fixed.
```
template '/etc/httpd/conf.modules.d/00-mpm.conf' do
  source '00-mpm.conf.erb'
  owner 'root'
  group 'root'
  mode '0644'
  notifies :restart, 'httpd_service[default]', :delayed
end
```

**Comment by someara** [comment]
I'll take a look at this later today.... 

though a quick glance, your hammer should read "/etc/httpd-default/conf.modules.d/00-mpm.conf"

**Comment by spliskamatyshak** [comment]
![image](https://cloud.githubusercontent.com/assets/8999522/8660165/e69c877a-2974-11e5-99e5-5253f017c0b4.png)

there are two conf.modules.d folders and it appears to be working on my system and the `00-mpm.conf` file installs to `/etc/httpd/conf.modules.d` automatically from your cookbook.  I override this and it works.

**Comment by spliskamatyshak** [comment]
I know 2.2 is strange regarding proving that worker is actually running (ps command that shows httpd.worker). Does 2.4 have a analogous oddity (It's not as simple as a ps command)? If so, what is it?

**Comment by someara** [comment]
Right. /etc/httpd is what the package drops off... the cookbook ignores it
(also, explicitly disables it) and sets up /etc/httpd-<instance_name>


Here's the a look-around when converging service24-single-centos-70 in
test-kitchen

https://gist.github.com/someara/bdd94ae81055981e7301

Looks good to me... can you gist an output of ps -ef ?

**Comment by someara** [comment]
Look at that. It's definitely using prefork...

https://gist.github.com/someara/f8218f6bbbcfe781320d

Investigating

**Comment by someara** [comment]
False alarm... that was with default config.

Systemd is starting it with a -f 

httpd-default -f /etc/httpd-default/conf/httpd.conf -V

Architecture:   64-bit
Server MPM:     event
  threaded:     yes (fixed thread count)
    forked:     yes (variable process count)
