### ISSUE TITLE
what is the 'mysite.conf.erb' files supposed to look like/contain?

### ISSUE THREAD

**Issue by joshoohaah** [chef-cookbooks/httpd#44]
I see your readme references some example like `mysite.conf.erb`.  Also in `httpd/test/fixtures/cookbooks/httpd_config_test/recipes/default.rb` there are some tests for `hello.conf.erb` and others.
I think some hello_world index files/examples are needed for this cookbook to show what structure/topology is needed to give some site information.

**Comment by someara** [comment]
It' supposed to look like.... whatever you want.
The test cookbooks are examples of that.

What exactly are you asking / suggesting?

-s

**Comment by iennae** [comment]
@joshoohaah I've added some documentation to the README to make it more clear about the httpd_config resource. https://github.com/chef-cookbooks/httpd#httpd_config 

Your comment about index files is separate. The resources within this community cookbook don't handle the website content. In the testing cookbooks, for example here https://github.com/chef-cookbooks/httpd/blob/dc951d170c3051742782f58a2e651cba1917994a/test/fixtures/cookbooks/hello_world_test/recipes/default.rb a very simple index file is added using a file resource to make sure that the webserver comes up with testable content.

If this hasn't resolved your question, please reopen. 

Thanks.
