### ISSUE TITLE
module file content

### ISSUE THREAD

**Issue by istopopoki** [chef-cookbooks/httpd#68]
Hi,
Unless I've missed something, I don't see a way to specify the content of a module .conf file through httpd_module. Would a 'source' parameter (similar to httpd_config) make sense ?
Something like:

httpd_module 'wsgi' do
  action :create
  source 'wsgi.conf.erb'
end

Thanks !

**Comment by iennae** [comment]
For the module resource it uses the filename parameter. If you look at the README though:

filename - The filename of the shared object to be rendered into the load config snippet. This can usually be omitted, and defaults to a generated value looked up in an internal map.

Check out the module resources in the libraries directory.

Based on the template name you are using though 'wsgi.conf.erb' that looks like you are wanting to also use the config resource which handles the configuration aspects of Apache. With that resource you have additional parameters:

* config_name - The name of the config on disk
* cookbook - The cookbook that the source template is found in. Defaults to the current cookbook.
* httpd_version - Used to calculate the configuration's disk path. Defaults to the platform's native Apache version.
* instance - The httpd_service instance the config is meant for. Defaults to 'default'
* source - The ERB format template source used to render the file.
* variables - A hash of variables passed to the underlying template resource

Of special interest here is that your wrapper cookbook would be where you have your templates defined so you don't need to fork the httpd cookbook.

Let me know if this explains your question or if you need additional help.

Thanks!

**Comment by iennae** [comment]
If you need additional help, please do reopen this issue. For now, I'm closing this issue. Thanks!
