### ISSUE TITLE
Small incongruency between docs and library code.

### ISSUE THREAD

**Issue by angelichorsey** [chef-cookbooks/httpd#69]
The README.md states:
> listen_ports - Ports that the server listens to. Defaults to ['80', '443'].

However, libraries/httpd_service.rb states:
> property :listen_ports, [String, Array], default: %w(80)

No big deal really, but thought you guys might want to remedy that.

**Comment by iennae** [comment]
@angelichorsey,

Thanks! Great eye. We'll get this fixed.

**Comment by iennae** [comment]
This has been updated in the README. Thanks again @angelichorsey!
