### ISSUE TITLE
httpd_module "php" doesn't work on Debian

### ISSUE THREAD

**Issue by eric-tucker** [chef-cookbooks/httpd#73]
```
  httpd_module "php" do
    action :create
  end
```

This throws an error that the package name must be specified on line 8 of the debian helper.

It does not appear to find the correct module to install.  Specifying php5 as the module name appears to work.

```
  httpd_module "php5" do
    action :create
  end
```

**Comment by iennae** [comment]
Can you explain more what you are expecting here? The name of the module is php5 on debian systems. On RHEL it's php.

**Comment by eric-tucker** [comment]
With LWRPs my opinion is that I should not have to change my Chef resource declaration when moving to a different OS.  I would have expected this cookbook to take care of translating all modules to their respective package installations for each OS.  I thought that was one of the shining features of Chef.  Portability.

Perhaps I'm wrong in this opinion, in which case this ticket can be closed.  Thanks.

**Comment by iennae** [comment]
@eric-tucker totally part of the benefit of Chef is to gain the portability. You've brought up a great point about something that could be implemented for this cookbook but isn't available yet. 

At this time this issue is not going to be worked on in the near future by my team. We do welcome community contributions, and I'm happy to review and pull in any work that solves you're reported issue.

Jennifer

**Comment by mohsin996** [comment]
if you are working with Ubuntu 16.0.4. It will throw error in kitchen converge, it complains about "No candidate version available for libapache2-mod-php5".

The solution can be, you can append below lines in your recipe json file.
# Install the mod_php Apache module.
httpd_module 'php7' do
instance 'default'
package_name 'php'
end

# Install php5-mysql.
package 'php-mysql' do
action :install
notifies :restart, 'httpd_service[default]'
end

#
This will install Apache php module and php-mysql in Ubuntu 16.
learn chef- writing a LAMP cookbook
link- https://learn.chef.io/modules/create-a-web-app-cookbook/ubuntu/virtualbox/configure-php#/

**Comment by mohsin996** [comment]
You may face problem with Ubuntu 16.04, if you use Chef to install php module as Chef wont supports ubuntu 16 as of now.
So when you do test kitchen converge to install Apache php module and php-mysql you may get error as "No candidate version available for libapache2-mod-php5

You can append this below code in you recipe json file.
# Install the mod_php5 Apache module.
  httpd_module 'php7' do
   instance 'default'
   package_name 'php'
  end

# Install php-mysql.
  package 'php-mysql' do
  action :install
  notifies :restart, 'httpd_service[default]'
  end
Link is -
https://learn.chef.io/modules/create-a-web-app-cookbook/ubuntu/virtualbox/configure-php#/

**Comment by mohsin996** [comment]
You may face problem with Ubuntu 16.04, if you use Chef to install php module as Chef wont supports ubuntu 16 as of now.
So when you do test kitchen converge to install Apache php module and php-mysql you may get error as "No candidate version available for libapache2-mod-php5

You can append this below code in you recipe json file.
# # Install the mod_php7 Apache module.
` ` `
  httpd_module 'php7' do
   instance 'default'
   package_name 'php'
  end
` ` `
# # Install php-mysql.
  ` ` ` 
package 'php-mysql' do
  action :install
  notifies :restart, 'httpd_service[default]'
  end
` ` `
[link to learn-chef!] (https://learn.chef.io/modules/create-a-web-app-cookbook/)
