### ISSUE TITLE
Default apache installation

### ISSUE THREAD

**Issue by angelichorsey** [chef-cookbooks/httpd#75]
Is it not currently possible to have a default httpd instance with this cookbook? Having apache_name set to "httpd-#{instance}" can cause confusion when using the httpd binary for troubleshooting.

E.g., I was looking to verify which modules were loaded with httpd-#{instance} -M and it shows the modules loaded in /etc/httpd/conf/ and not /etc/httpd-#{instance}/conf.

**Comment by tas50** [comment]
The design of this cookbook is to support instanced installs.  The apache2 cookbook is probably better suited if you're looking for an out of the box single install.
