### ISSUE TITLE
Resolve Foodcritic FC005 / FC023 warnings

### ISSUE THREAD

**Issue by tas50** [chef-cookbooks/httpd#79]
### Cookbook version

master
### Chef-client version

12.9.38
### Platform Details

All

FC005: Avoid repetition of resource declarations: ./libraries/httpd_service_debian.rb:144
FC005: Avoid repetition of resource declarations: ./libraries/httpd_service_debian.rb:304
FC023: Prefer conditional attributes: ./libraries/httpd_service_debian.rb:224
FC023: Prefer conditional attributes: ./libraries/httpd_service_rhel.rb:125
FC023: Prefer conditional attributes: ./libraries/httpd_service_rhel.rb:269
FC023: Prefer conditional attributes: ./libraries/httpd_service_rhel_systemd.rb:6
FC023: Prefer conditional attributes: ./libraries/httpd_service_rhel_sysvinit.rb:5

**Comment by iennae** [comment]
FC005 is resolved. FC023 has a few remaining issues as it incorrectly warns on provides which does not implement only_if and not_if.
