### ISSUE TITLE
recent change caused httpd to fail with "cannot load such file -- chef_compat/resource"

### ISSUE THREAD

**Issue by pnemere** [chef-cookbooks/httpd#95]
As of this morning (few hours ago) I can't seem to converge anything that uses the httpd cookbook. I thought it was my dev machine, reinstalled chefdk, etc and still happening. Error message can be found at the end.

### Cookbook version
0.4.0 and 0.3.6

### Chef-client version
Host machine running 12.11.18, guest VM running 12.14.60

### Platform Details
OSX, Vagrant, Virtualbox

### Scenario:
Simply including httpd into metadata.rb and Berksfile causes the above error. Wasn't happening till a few hours ago. Suspecting either a new verison of httpd or chefcompat cookbook has started appearing on my guest VM

### Steps to Reproduce:

1. chef generate cookbook httpduser
2. edit metadata.rb, add "depends 'httpd'" at the end
3. edit Berksfile, add "cookbook 'httpd', '~> 0.4.0'" at the end. Also tried with "cookbook 'httpd', '~> 0.3.6'" 
4. edit .kitchen.yml to use a platform/box you intend, I used:
```
platforms:
- name: bento/centos-7.2
```

Run kitchen converge, the above error happens.

### Expected Result:
Expecting the converge to finish (httpduser cookbook constructed in reproduction steps doesn't actually do anything, default.rb is blank!).

### Actual Result:

```
Synchronizing Cookbooks:
         - httpduser (0.1.0)
         - httpd (0.4.0)
         - compat_resource (12.14.3)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       
       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/httpd/libraries/helpers.rb
       ================================================================================
       
       LoadError
       ---------
       cannot load such file -- chef_compat/resource
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/httpd/libraries/helpers.rb:1:in `<top (required)>'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/httpd/libraries/helpers.rb:
       
         1>> require 'chef_compat/resource'
         2:  
         3:  module HttpdCookbook
         4:    module Helpers
         5:      def default_apache_version
         6:        return '2.2' if node['platform_family'] == 'debian' && node['platform_version'].to_i == 7
         7:        return '2.2' if node['platform_family'] == 'debian' && node['platform_version'] == '12.04'
         8:        return '2.2' if node['platform_family'] == 'debian' && node['platform_version'].to_i == 6
         9:        return '2.2' if node['platform_family'] == 'debian' && node['platform_version'].to_i == 7
        10:        return '2.2' if node['platform_family'] == 'omnios'
       
       Platform:
       ---------
       x86_64-linux
       
       
       Running handlers:
       [2016-09-15T04:48:48+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-09-15T04:48:48+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 05 seconds
       [2016-09-15T04:48:48+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-09-15T04:48:48+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-09-15T04:48:48+00:00] ERROR: cannot load such file -- chef_compat/resource
       [2016-09-15T04:48:48+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by vanetix** [comment]
Can confirm this issue, I receive this same cookbook compilation error with chef-client `12.14.60`, but not on `12.13.37`.

**Comment by FabricioPavano** [comment]
Can confirm too
chef-client: 12.13.37

**Comment by cohenaj194** [comment]
I can confirm too.  See my comment on stack exchange and learn.chef.io:
http://stackoverflow.com/questions/39561626/chef-cant-use-depends-httpd-in-metadata-rb
https://learn.chef.io/manage-a-web-app/rhel/configure-apache/

Chef Development Kit Version: 0.17.17

chef-client version: 12.13.37

berks version: 4.3.5

kitchen version: 1.11.1

**Comment by pnemere** [comment]
@cohenaj194 Looking at your stackoverflow log, the actual chef-client version you're using is:
Starting Chef Client, version 12.14.60

That's the chef client inside your VM (guest) which is the one to look for in this instance. Perhaps the version you pasted is the one running on your host machine.

I've found if I force kitchen to install the older chef client, I can get this to work.

Here is what I did (top of .kitchen.yml):
`---
driver:
  name: vagrant
  require_chef_omnibus: 12.13.37
`
Obviously this is only a temporary workaround to use the old chef client while we wait for a fix for the new version. You will need to remember to remove this line when the new version is fixed!

**Comment by cohenaj194** [comment]
That worked, your comment formatting is a bit off though, heres what my working `.kitchen.yml` looked like exactly:

    ---
    driver:
      name: vagrant
      require_chef_omnibus: 12.13.37
    
    provisioner:
      name: chef_zero
    
    verifier:
      name: inspec
    
    platforms:
      - name: centos-7.2
    
    suites:
      - name: default
        run_list:
          - recipe[webserver_test::default]
        verifier:
          inspec_tests:
            - test/recipes
        attributes:

**Comment by pnemere** [comment]
Ah yes sorry I didn't check my post after typing it... thanks for posting the working version!

**Comment by karmix** [comment]
The compat_resource cookbook backports bits of code so you can use some of the newer chef features with older clients.  It has no use on a modern client, so the cookbook no longer adds itself to the `$LOAD_PATH` unless it is running on what it recognizes to be an old version of chef-client.  When the cookbook does not add itself to the `$LOAD_PATH`, the httpd cookbook cannot locate `chef_compat/resource` and raises a `LoadError`.

As @pnemere pointed out, the easiest work around for this issue is to not use the latest version of chef-client.  Specifically, use a version of chef-client that is lower than the version listed in the `files/lib/chef_upstream-version.rb` of the compat_resource cookbook you are using.

**Comment by lamont-granquist** [comment]
The `require 'chef_compat/resource'` can probably be deleted and that is most likely the best route out of this mess.

**Comment by lamont-granquist** [comment]
hurm, yeah, i just went down the route of trying to make this work in the cookbook and its likely to be a bit of a mess, and i'm not getting it solved tonight.

i'll probably need to point at some other path which only contains the empty chef_compat/resource.rb file, pretty much only to fix this cookbook, which suggests to me that this cookbook needs fixing.

**Comment by lamont-granquist** [comment]
note that our guidance is to no longer write "library-style resources" like in this cookbook in order to avoid issues exactly like this one:

https://docs.chef.io/custom_resources_notes.html

**Comment by karmix** [comment]
@lamont-granquist: If you found something that still requires compat_resource, I think it would be cleaner if I update the PR to simply
```Ruby
begin
  require 'chef_compat/resource'
rescue LoadError
end
```
instead of creating an empty `chef_compat/resource.rb`.

**Comment by lamont-granquist** [comment]
I'm not even certain you need to do that -- since this cookbook depends on compat_resource its libraries files are loaded first, so I don't think there's any point to the requires line at all.

But yeah, that would also certainly work if I've missed something.
