### ISSUE TITLE
httpd_service is broken in 0.4.2

### ISSUE THREAD

**Issue by tpetchel** [chef-cookbooks/httpd#97]
### Cookbook version
0.4.2

### Chef-client version
12.14.89

### Platform Details
Seen on `bento/ubuntu-14.04` and `bento/centos-7.2`, both running on Vagrant/VirtualBox.

### Scenario:
`httpd_service` produces an error. For example, 

```
httpd_service 'customers' do
  mpm 'prefork'
  action [:create, :start]
end
```

produces an error like:

```
ERROR: httpd_service_rhel_systemd[customers] (awesome_customers_rhel::web line 7) had an error: ArgumentError: directory[/etc/httpd-customers/conf.modules.d] (/tmp/kitchen/cache/cookbooks/httpd/libraries/httpd_service_rhel.rb line 115) had an error: ArgumentError: wrong number of arguments (given 0, expected 1)
```

### Steps to Reproduce:

Add a `httpd_service` resource to any recipe. Alternatively:

1. Clone https://github.com/learn-chef/awesome_customers_rhel or 

  https://github.com/learn-chef/awesome_customers_ubuntu 
1. Update metadata.rb (`depends 'httpd', '~> 0.4.2'`)
1. Run `kitchen converge`

I've been told it's the latest compat_resource cookbook that breaks things, but I don't understand all the details.

**Comment by iennae** [comment]
Additional information with          - httpd (0.3.6)

The issue will be 

LoadError
       ---------
       cannot load such file -- chef_compat/resource

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/httpd/libraries/helpers.rb:1:in `<top (required)>'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/httpd/libraries/helpers.rb:

         1>> require 'chef_compat/resource'
         2:
         3:  module HttpdCookbook
         4:    module Helpers
         5:      def default_apache_version
         6:        return '2.2' if node['platform_family'] == 'debian' && node['platform_version'] == '10.04'
         7:        return '2.2' if node['platform_family'] == 'debian' && node['platform_version'] == '12.04'
         8:        return '2.2' if node['platform_family'] == 'debian' && node['platform_version'] == '13.04'
         9:        return '2.2' if node['platform_family'] == 'debian' && node['platform_version'] == '13.10'
        10:        return '2.2' if node['platform_family'] == 'debian' && node['platform_version'].to_i == 6
